server:
  port: 7001

spring:
  application:
    name: detect-flow
  datasource:
    username: root
    password: huangpei120
    url: jdbc:mysql://39.108.220.199:3306/ai-detect?characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000