spring:
  application:
    name: detect-zuul
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 9000

zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    api-user:
      path: /detect-user/**
      service-id: detect-user
    api-camera:
      path: /detect-camera/api/v1/**
      service-id: detect-camera
    api-analyze:
      path: /flow-analyze/**
      service-id: flow-analyze
    api-flow:
      path: /detect-flow/**
      service-id: detect-flow
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000


hystrix:
  metrics:
    polling-interval-ms: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/